### ISSUE TITLE
Sorting servers by players is broken

### ISSUE THREAD

**Issue by OrfeasZ** [EmulatorNexus/Fusion-UI#16]
![](https://i.imgur.com/T3EuAqQ.png)

**Comment by chelentos** [comment]
I think that the key of the problem might be [here](https://github.com/EmulatorNexus/Fusion-UI/blob/master/app/components/ServerEntry.js#L137).

[Functions of sorting](https://github.com/EmulatorNexus/Fusion-UI/blob/master/app/reducers/servers.js#L94) sort servers not by `variables.players`, but when you display servers you display value from `variables.players` if it's not `NaN`.

So i think when values in `server.players` and `server.variables.players` are different, users can see this bug.

I don't have enough knowledge bout values in `server.variables`, but if you tell me, i can try to fix this bug.

**Comment by OrfeasZ** [comment]
I think you're absolutely right. The `players` key under `variables` is basically a server-controlled counter, whereas `server.players` is provided by the backend. When `server.variables.players` is specified, it overrides whatever player count the backend thinks is valid, since in cases where people disconnect from the backend but not from the server, the backend count can become invalid.

You can go ahead and fix this if you feel up for it.

**Comment by FlashHit** [comment]
This can be closed I think @OrfeasZ
