### ISSUE TITLE
[Req] Add ModSettings

### ISSUE THREAD

**Issue by FlashHit** [EmulatorNexus/Fusion-UI#6]
Atm clients can’t edit ModSettings due to the missing ui implementation.

**Comment by kapraran** [comment]
Some more info will be needed about the structure of the modsetting for each type.
Is this posted somewhere? Or can you update test.js with some mock data for modSettings? @OrfeasZ

**Comment by paulhobbel** [comment]
We have some capacity left in the UI team of Reality Mod, we will pick this up

**Comment by FlashHit** [comment]
And it should be possible to delete ModSettings of inactive mods.

**Comment by FlashHit** [comment]
Implemented in 19412.
