### ISSUE TITLE
[Bug] Not being able to type password if a server has performance issues.

### ISSUE THREAD

**Issue by FlashHit** [EmulatorNexus/Fusion-UI#8]
See here:
https://github.com/EmulatorNexus/VeniceUnleashed/issues/734

**Comment by kapraran** [comment]
There seems to be existing code that handles this case, and in the browser it works, so maybe it was fixed?

**Comment by FlashHit** [comment]
No clue 🤷‍♂️

**Comment by FlashHit** [comment]
Was able to verify this. If you click join anyways the popup just disappears but you won’t join nor be able to type in a password.

**Comment by FlashHit** [comment]
PR: 
- https://github.com/EmulatorNexus/Fusion-UI/pull/28
